import { Courier_Prime, PT_Sans } from "next/font/google";
import CartProvider from './context/CartContext';
import NavBar from '@/components/NavBar/NavBar';
import Footer from '@/components/Footer/Footer';
import "./globals.css";

const courierPrime = Courier_Prime({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-courier-prime',
})

const ptSans = PT_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-pt-sans',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${courierPrime.variable} ${ptSans.variable}`}>
        <CartProvider>
          <NavBar/>
          <main>
            { children }
          </main>
        </CartProvider>
        <Footer/>
      </body>
    </html>
  );
}
