import { Geist, Geist_Mono, Space_Grotesk, DM_Sans } from "next/font/google";
import CartProvider from './context/CartContext';
import NavBar from '@/components/NavBar/NavBar';
import Footer from '@/components/Footer/Footer';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({ 
  subsets: ['latin'],
  variable: '--font-space-grotesk'
 });

const dmSans = DM_Sans({ 
  subsets:['latin'],
  variable: '--font-dm-sans'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable} ${dmSans.variable}`}>
        <CartProvider>
          <NavBar/>
          <main>
            { children }
          </main>
        </CartProvider>
        <Footer/>
      </body>
    </html>
  );
}
